version: '3'
services:
  app:
    build:
      ./userAppProject
    environment:
      USER: "$USER" 
      HOST: "$HOST"
      PORT: "$PORT"
      PASSWORD: "$PASSWORD"
      DATABASE: "$DATABASE"
      SECRET_KEY: "$SECRET_KEY"
    depends_on:
      - mysql_db
    restart: always
    links:
      - mysql_db
    ports:
      - 8080:5000
    expose:
      - '5000'
    volumes:
      - ./userAppProject:/userAppProject
  mysql_db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "$PASSWORD"
    ports:
      - 3308:3306
    expose:
      - '3306'
    volumes: 
      - ./setupDataBase:/docker-entrypoint-initdb.d/:ro

  
  
